########################################################
##### Configuration file for gh-pr-stats-retriever #####
########################################################

### PRs to retrieve

# Owner of the repository (in github urls, example: fabien-marty)
# (can be overriden by the command line argument --owner)
owner = ""

# Repository (without slashes, example: gh-pull-requests-stats-retriever)
# (can be overriden by the command line argument --owner)
repo = ""

#[[select_prs]]
#state = "open" # state of the PR: open, closed or all

[[select_prs]]
state = "closed"           # state of the PR: open, closed or all
updated_seconds = 31536000 # PRs updated in the last X seconds (if the keyword is not present or if X <= 0, it will be ignored)
# FIXME

### Statistics to retrieve

[labels_stats]
enabled = true
labels = [
    [
        "PR: Review TODO",
    ],
    [
        "PR: Review OK",
        "No QA",
        "-On Hold",
        "-on hold",
        "-on hold infra",
        "-No merge to devel",
    ],
    [
        "PR: Review OK",
        "QA - OK",            # QA: OK
        "-On Hold",
        "-on hold",
        "-on hold infra",
        "-No merge to devel",
    ],
]
