name: CI

on:
    push:
        branches:
            - master
            - dev
    pull_request:

jobs:
    main_ci:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: "1.21"
            - name: Run build
              run: |
                make build
            - name: Run lint
              run: |
                make FIX=0 lint
            - name: Run test
              run: |
                make test
            - name: Run git checks
              run: |
                N=`git diff |wc -l`
                if test ${N} -gt 0; then
                  echo "ERROR: some GIT files were modified"
                  git status
                  git diff
                  exit 1
                fi
            - name: Run clean
              run: |
                make FIX=0 clean